#!/bin/sh

MYDIR=$(dirname $0)
ROOTDIR=$MYDIR/..
GVF=$ROOTDIR/GIT-VERSION-FILE
DEF_VER=v0.3.4.GIT

LF='
'

# First see if there is a version file (included in release tarballs),
# then try git-describe, then default.
if test -f $ROOTDIR/version
then
	VN=$(cat version) || VN="$DEF_VER"
elif test -d $ROOTDIR/.git -o -f .git &&
	VN=$(git describe --match "v[0-9]*" --abbrev=7 --always HEAD 2>/dev/null) &&
	case "$VN" in
	*$LF*) (exit 1) ;;
	v[0-9]*)
		git update-index -q --refresh
		test -z "$(git diff-index --name-only HEAD --)" ||
		VN="$VN-dirty" ;;
	esac
then
	VN=$(echo "$VN" | sed -e 's/-/./g' | sed -e 's/.rc/-rc/' | sed -e 's/.pre/-pre/' | sed -e 's/.beta/-beta/' | sed -e 's/.alpha/-alpha/');
else
	VN="$DEF_VER"
fi

VN=$(expr "$VN" : v*'\(.*\)')

if test -r $GVF
then
	VC=$(sed -e 's/^GIT_VERSION = //' < $GVF)
else
	VC=unset
fi
test "$VN" = "$VC" || {
	echo >&2 "GIT_VERSION = $VN"
	echo "GIT_VERSION = $VN" > $GVF
}
